---
spring:
  config:
    activate:
      on-profile: sentence
  application:
    name: sentence
eureka:
  instance: 
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: 'https://${eureka.instance.hostName}:${server.port}/info'
    healthCheckUrl: 'https://${eureka.instance.hostName}:${server.port}/health'
    homePageUrl: 'https://${eureka.instance.hostName}:${server.port}/'
