#---
#spring:
#  config:
#    activate:
#      on-profile: subject
#words: I,You,He,She,It
#
---
# spring:
#   config:
#     activate:
#       on-profile: verb
# words: ran,knew,had,saw,bought
#
#---
#spring:
#  config:
#    activate:
#      on-profile: article
#words: a,the
#
#---
#spring:
#  config:
#    activate:
#      on-profile: adjective
#words: reasonable,leaky,suspicious,ordinary,unlikely
#
#---
#spring:
#  config:
#    activate:
#      on-profile: noun
#words: boat,book,vote,seat,backpack,partition,groundhog
# Allow Eureka to recognize two apps of the same type on the same host as separate instances:
---
wordconfig:
  luckyWord: udasbhifafnak
  preamble: My lucky word is 

  

# ---
# spring:
#   application:
#     name: verb
#   config:
#     activate:
#       on-profile: verb
      
# ---
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8010/eureka/
#   instance:
#     instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
