---
spring:
  config:
    activate:
      on-profile: magicword
  application:
    name: magicword
words: alakazam, boombaboom, tadam
server:
  port: 8100
  ssl:
    enabled: true
    key-store: 'C:\Users\user1\Desktop\Udemy projects\Lab6\word server\src\main\resources\keystore.p12' #path-ul
    key-store-password: password #parola pt keystore
    key-store-type: PKCS12 #tipul de cheie (pkcs12 sau JKS)
    key-alias: springboot #numele ce identifica cheia in keystore
feign:
 httpclient:
  disableSslValidation: true
logging:
  level:
    root: DEBUG
